# SPDX-License-Identifier: GPL-3.0-or-later
"""ComplexMixerBlock — see :class:`ComplexMixerBlock`."""
import math
from typing import Any, Dict, List, Tuple

import numpy as np

from ..block import CellProgram, DataWord, EntryPoint, Port, StateVar
from ._base import BlockInterface, KyttarBlock, float_to_q15


class ComplexMixerBlock(KyttarBlock):
    """
    Complex Mixer / Frequency Shifter — drop-in for GNU Radio
    ``blocks.multiply_cc(signal, analog.sig_source_c(...))``: multiplies a complex
    input signal by a complex exponential, shifting it in frequency.

        out[n] = in[n] · exp(jθ_n),   θ_n = 2π · frequency/sample_rate · n
        yi = xi·cos θ_n − xq·sin θ_n
        yq = xi·sin θ_n + xq·cos θ_n   (the FULL complex product, multiply_cc)

    The complex exponential is generated by the SAME interpolated quarter-wave NCO
    as :class:`NCOBlock` (angle-fold + parity-split 33-entry table, idx_bits=7,
    ~11 LSB). Unlike the older single-axis ``in·cos`` mixer this is the true
    ``multiply_cc`` (both quadrature arms).

    Parameters mirror GRC's Signal Source (the mixing oscillator) in DSP units:
    ``sample_rate`` (Hz) and ``frequency`` (Hz, the shift; ``freq_word`` derived).

    Interface: COMPLEX input (the signal, xi@R0 / xq@R1) and COMPLEX output (yi, yq).
    Each input sample triggers one output; n=0 multiplies by exp(j·0)=1 (phase-0).

    The input signal is carried to the output ``mixer`` cell through a cheap
    ``relay`` cell placed MID-pipeline: a value forwarded across too many cells of a
    long datapath does not deliver (a substrate forward-distance limit -- phase→last
    over 8 skipped cells arrives 0), so xi/xq hop phase→relay (skip 4)→mixer (skip
    4), each within the proven distance.
    """
    CATEGORY = "modulation"
    TAGS = ["mixer", "frequency_shift", "multiply_cc", "modulation"]

    TABLE_SIZE = 33

    _interface = BlockInterface(
        entry_address=1, input_registers=[0, 1], output_registers=[0, 1])

    _CELL_IDS = ["phase",
                 "sin_fold", "sin_even", "sin_odd", "sin_interp", "relay",
                 "cos_fold", "cos_even", "cos_odd", "cos_interp", "mixer"]

    def __init__(self, name: str, sample_rate: float = 32000.0,
                 frequency: float = 2000.0):
        super().__init__(name, sample_rate=sample_rate, frequency=frequency)
        self._sample_rate = float(sample_rate)
        self._frequency = float(frequency)
        self._freq_word = round(self._frequency / self._sample_rate * 65536) & 0xFFFF
        self._phase = 0

    @property
    def cell_count(self) -> int:
        return 11

    @property
    def interface(self) -> BlockInterface:
        return self._interface

    @property
    def frequency(self) -> float:
        return self._frequency

    @property
    def freq_word(self) -> int:
        return self._freq_word

    def _quarter_table(self) -> List[int]:
        return [min(32767, int(round(math.sin((math.pi / 2) * k / 32) * 32768))) & 0xFFFF
                for k in range(self.TABLE_SIZE)]

    def _even_odd_tables(self):
        t = self._quarter_table()
        even = [t[2 * j] for j in range(17)]
        odd = [t[2 * j + 1] for j in range(16)] + [0]
        return even, odd

    # ------------------------------------------------------------------ cells
    def build_cell_programs(self) -> Dict[str, CellProgram]:
        even_tbl, odd_tbl = self._even_odd_tables()

        phase_cell = CellProgram(
            inputs=[Port("xi", register=0), Port("xq", register=1)],
            outputs=[Port("ph_sin"), Port("ph_cos"), Port("xi_fwd"),
                     Port("xq_fwd"), Port("trig")],
            entries=[EntryPoint("default")],
            data=[DataWord("freq", self._freq_word, address=4),
                  DataWord("quarter", 16384, address=5)],
            state=[StateVar("phase"), StateVar("xis"), StateVar("xqs")],
            assembly_template="""\
start:
    MOVE R{state:xis}, R{in:xi}
    MOVE R{state:xqs}, R{in:xq}
    MOVE R0, R{state:phase}
    {write:ph_sin}
    ADD R{state:phase}, R{data:quarter}
    {write:ph_cos}
    MOVE R0, R{state:xis}
    {write:xi_fwd}
    MOVE R0, R{state:xqs}
    {write:xq_fwd}
    ADD R{state:phase}, R{data:freq}
    MOVE R{state:phase}, R0
    {jump:trig}
""",
        )

        # relay: hold and re-forward the signal mid-pipeline (skip-4 each hop).
        relay_cell = CellProgram(
            inputs=[Port("xi", register=0), Port("xq", register=1)],
            outputs=[Port("xi_fwd"), Port("xq_fwd"), Port("trig")],
            entries=[EntryPoint("default")],
            data=[],
            state=[StateVar("xis"), StateVar("xqs")],
            assembly_template="""\
start:
    MOVE R{state:xis}, R{in:xi}
    MOVE R{state:xqs}, R{in:xq}
    MOVE R0, R{state:xis}
    {write:xi_fwd}
    MOVE R0, R{state:xqs}
    {write:xq_fwd}
    {jump:trig}
""",
        )

        def _fold_cell():
            return CellProgram(
                inputs=[Port("phase", register=0)],
                outputs=[Port("idx_e"), Port("idx_o"), Port("frac"), Port("neg"),
                         Port("trig")],
                entries=[EntryPoint("default")],
                data=[DataWord("mask3fff", 0x3FFF, address=1),
                      DataWord("one", 1, address=2),
                      DataWord("c16384", 16384, address=3),
                      DataWord("zero", 0, address=4)],
                state=[StateVar("ph"), StateVar("w"), StateVar("mir")],
                assembly_template="""\
start:
    MOVE R{state:ph}, R{in:phase}
    MOVE R{state:w}, R{state:ph}
    AND R{state:w}, R{data:mask3fff}
    MOVE R{state:w}, R0
    MOVE R{state:mir}, R{state:ph}
    SHR R{state:mir}, #14
    MOVE R{state:mir}, R0
    SHR R{state:mir}, #1
    {write:neg}
    AND R{state:mir}, R{data:one}
    CMP R0, R{data:zero}
    BR.Z nomir
    SUB R{data:c16384}, R{state:w}
    MOVE R{state:w}, R0
nomir:
    MOVE R{state:ph}, R{state:w}
    SHL R{state:ph}, #7
    MOVE R{state:ph}, R0
    SHR R{state:ph}, #1
    {write:frac}
    SHR R{state:w}, #9
    {write:idx_e}
    {write:idx_o}
    {jump:trig}
""",
            )

        def _even_cell():
            data = [DataWord(f"e{j}", v, address=1 + j) for j, v in enumerate(even_tbl)]
            data += [DataWord("one", 1, address=1 + len(even_tbl))]
            return CellProgram(
                inputs=[Port("idx", register=0)],
                outputs=[Port("eval"), Port("par"), Port("trig")],
                entries=[EntryPoint("default")],
                data=data, state=[StateVar("p")],
                assembly_template="""\
start:
    MOVE R{state:p}, R{in:idx}
    AND R{state:p}, R{data:one}
    {write:par}
    ADD R{state:p}, R0
    MOVE R{state:p}, R0
    SHR R{state:p}, #1
    MOVE R{state:p}, R0
    ADD R{state:p}, R{data:one}
    LOAD R0
    {write:eval}
    {jump:trig}
""",
            )

        def _odd_cell():
            data = [DataWord(f"o{j}", v, address=1 + j) for j, v in enumerate(odd_tbl)]
            data += [DataWord("one", 1, address=1 + len(odd_tbl))]
            return CellProgram(
                inputs=[Port("idx", register=0)],
                outputs=[Port("oval"), Port("trig")],
                entries=[EntryPoint("default")],
                data=data, state=[StateVar("p")],
                assembly_template="""\
start:
    MOVE R{state:p}, R{in:idx}
    AND R{state:p}, R{data:one}
    SUB R{state:p}, R0
    MOVE R{state:p}, R0
    SHR R{state:p}, #1
    MOVE R{state:p}, R0
    ADD R{state:p}, R{data:one}
    LOAD R0
    {write:oval}
    {jump:trig}
""",
            )

        def _interp_cell():
            return CellProgram(
                inputs=[Port("eval", register=0), Port("oval", register=1),
                        Port("par", register=2), Port("frac", register=3),
                        Port("neg", register=4)],
                outputs=[Port("val"), Port("trig")],
                entries=[EntryPoint("default")],
                data=[DataWord("zero", 0, address=5)],
                state=[StateVar("p"), StateVar("Pe"), StateVar("Po"), StateVar("d")],
                assembly_template="""\
start:
    MOVE R{state:Pe}, R{in:eval}
    MOVE R{state:Po}, R{in:oval}
    CMP R{in:par}, R{data:zero}
    BR.Z evencase
    MOVE R{state:p}, R{state:Pe}
    MOVE R{state:Pe}, R{state:Po}
    MOVE R{state:Po}, R{state:p}
evencase:
    SUB R{state:Po}, R{state:Pe}
    MOVE R{state:d}, R0
    MULQ R{state:d}, R{in:frac}
    MOVE R{state:d}, R0
    ADD R{state:d}, R{state:Pe}
    MOVE R{state:d}, R0
    CMP R{in:neg}, R{data:zero}
    BR.Z out
    SUB R{data:zero}, R{state:d}
    MOVE R{state:d}, R0
out:
    MOVE R0, R{state:d}
    {write:val}
    {jump:trig}
""",
            )

        mixer_cell = CellProgram(
            inputs=[Port("cosv", register=0), Port("sinv", register=1),
                    Port("xi", register=2), Port("xq", register=3)],
            outputs=[Port("yi"), Port("yq"), Port("trig")],
            entries=[EntryPoint("default")],
            data=[DataWord("zero", 0, address=4)],
            state=[StateVar("c"), StateVar("s"), StateVar("xi2"), StateVar("xq2"),
                   StateVar("acc"), StateVar("t")],
            assembly_template="""\
start:
    MOVE R{state:c}, R{in:cosv}
    MOVE R{state:s}, R{in:sinv}
    MOVE R{state:xi2}, R{in:xi}
    MOVE R{state:xq2}, R{in:xq}
    MOVE R{state:t}, R{state:xi2}
    MULQ R{state:t}, R{state:c}
    MOVE R{state:acc}, R0
    MOVE R{state:t}, R{state:xq2}
    MULQ R{state:t}, R{state:s}
    SUB R{state:acc}, R0
    {write:yi}
    MOVE R{state:t}, R{state:xi2}
    MULQ R{state:t}, R{state:s}
    MOVE R{state:acc}, R0
    MOVE R{state:t}, R{state:xq2}
    MULQ R{state:t}, R{state:c}
    ADD R{state:acc}, R0
    {write:yq}
    {jump:trig}
""",
        )

        return {
            "phase": phase_cell,
            "sin_fold": _fold_cell(), "sin_even": _even_cell(),
            "sin_odd": _odd_cell(), "sin_interp": _interp_cell(),
            "relay": relay_cell,
            "cos_fold": _fold_cell(), "cos_even": _even_cell(),
            "cos_odd": _odd_cell(), "cos_interp": _interp_cell(),
            "mixer": mixer_cell,
        }

    def internal_connections(self) -> List[Tuple[str, str, str, str]]:
        conns = [
            ("phase", "ph_sin", "sin_fold", "phase"),
            ("phase", "ph_cos", "cos_fold", "phase"),
            ("phase", "xi_fwd", "relay", "xi"),
            ("phase", "xq_fwd", "relay", "xq"),
            ("relay", "xi_fwd", "mixer", "xi"),
            ("relay", "xq_fwd", "mixer", "xq"),
        ]
        for ch in ("sin", "cos"):
            conns += [
                (f"{ch}_fold", "idx_e", f"{ch}_even", "idx"),
                (f"{ch}_fold", "idx_o", f"{ch}_odd", "idx"),
                (f"{ch}_fold", "frac", f"{ch}_interp", "frac"),
                (f"{ch}_fold", "neg", f"{ch}_interp", "neg"),
                (f"{ch}_even", "eval", f"{ch}_interp", "eval"),
                (f"{ch}_even", "par", f"{ch}_interp", "par"),
                (f"{ch}_odd", "oval", f"{ch}_interp", "oval"),
            ]
        conns += [
            ("sin_interp", "val", "mixer", "sinv"),
            ("cos_interp", "val", "mixer", "cosv"),
        ]
        return conns

    def internal_jumps(self) -> List[Tuple[str, str, str, str]]:
        chain = ["phase", "sin_fold", "sin_even", "sin_odd", "sin_interp", "relay",
                 "cos_fold", "cos_even", "cos_odd", "cos_interp", "mixer"]
        return [(chain[i], "trig", chain[i + 1], "default")
                for i in range(len(chain) - 1)]

    def output_cell_ids(self) -> List[str]:
        return ["mixer"]

    def default_layout(self) -> Dict[Any, Tuple[int, int, str]]:
        col0 = ["phase", "sin_fold", "sin_even", "sin_odd", "sin_interp", "relay"]
        col1_bottom_up = ["cos_fold", "cos_even", "cos_odd", "cos_interp", "mixer"]
        layout = {}
        for j, cid in enumerate(col0):
            face = "east" if cid == "relay" else "south"
            layout[cid] = (0, j, face)
        for k, cid in enumerate(col1_bottom_up):
            face = "east" if cid == "mixer" else "north"
            layout[cid] = (1, 5 - k, face)
        return layout

    # -------------------------------------------------------------- reference
    @staticmethod
    def _s16(v):
        v &= 0xFFFF
        return v - 0x10000 if v >= 0x8000 else v

    def _signed_sine_q15(self, phase16: int, tbl: List[int]) -> int:
        s16 = self._s16
        phase16 &= 0xFFFF
        within = phase16 & 0x3FFF
        neg = phase16 >> 15
        mir = (phase16 >> 14) & 1
        q = (16384 - within) if mir else within
        idx = q >> 9
        frac = (q & 0x1FF) << 6
        P = s16(tbl[idx])
        Q = s16(tbl[idx + 1]) if idx < 32 else P
        mag = P + ((s16((Q - P) & 0xFFFF) * frac) >> 15)
        return -mag if neg else mag

    def process_reference_q15(self, input_iq) -> List[Tuple[int, int]]:
        """Bit-exact predictor: out = in · exp(jθ_n) via the on-chip interpolated
        cos/sin and the Q15 complex product."""
        tbl = self._quarter_table()
        s16 = self._s16
        arr = np.asarray(input_iq)
        if np.iscomplexobj(arr):
            xs = [(float_to_q15(c.real), float_to_q15(c.imag)) for c in arr]
        elif arr.ndim == 2 and arr.shape[1] == 2:
            xs = [(int(x) & 0xFFFF, int(y) & 0xFFFF) for x, y in arr]
        else:
            xs = [(float_to_q15(float(x)), 0) for x in arr]
        out = []
        phase = 0
        for (xi, xq) in xs:
            cos = self._signed_sine_q15((phase + 16384) & 0xFFFF, tbl)
            sin = self._signed_sine_q15(phase, tbl)
            xi_s, xq_s = s16(xi), s16(xq)
            yi = ((xi_s * cos) >> 15) - ((xq_s * sin) >> 15)
            yq = ((xi_s * sin) >> 15) + ((xq_s * cos) >> 15)
            out.append((yi & 0xFFFF, yq & 0xFFFF))
            phase = (phase + self._freq_word) & 0xFFFF
        return out

    def process_reference(self, input_samples) -> np.ndarray:
        ref = self.process_reference_q15(input_samples)
        return np.array([complex(self._s16(yi) / 32768.0, self._s16(yq) / 32768.0)
                         for yi, yq in ref], dtype=np.complex64)

    def reset(self):
        self._phase = 0
