# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the block-status dashboard (STATUS.md) from the manifest + reports.

The dashboard is GENERATED, never hand-edited. Source of truth:
  * ``verification/manifest.json`` — the curated target list with per-block scope,
    status, GRC counterpart, and notes; AND
  * ``verification/reports/<KyttarBlock>.json`` — a metrics record emitted by a
    block's verification run (pass, max_abs_err, nmse_db, correlation, coverage).

A block's row shows its manifest status; when a matching report exists, the row is
enriched with the measured quality metrics. This keeps the table honest — metrics
are measured, not typed — and makes a contributor's PR a clean diff (new manifest
row + report + regenerated table row).

Usage:
    python verification/tools/gen_dashboard.py            # write STATUS.md
    python verification/tools/gen_dashboard.py --check     # exit 1 if stale (CI)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_VERIFY = Path(__file__).resolve().parents[1]
_REPO = _VERIFY.parent
MANIFEST = _VERIFY / "manifest.json"
REPORTS = _VERIFY / "reports"
STATUS = _VERIFY / "STATUS.md"
README = _REPO / "README.md"

# README block-status summary is regenerated between these markers.
_README_BEGIN = "<!-- BLOCK-STATUS:BEGIN (generated by verification/tools/gen_dashboard.py) -->"
_README_END = "<!-- BLOCK-STATUS:END -->"

_STATUS_ICON = {
    "done": "✅ done",
    "in_progress": "🟡 in progress",
    "planned": "⬜ planned",
    "wont_map": "⛔ won't map",
}
_TIER_LABEL = {1: "1 · feed-forward", 2: "2 · stateful/loop", 3: "3 · new GRC block"}


def _load_report(kyttar_block: str) -> dict | None:
    p = REPORTS / f"{kyttar_block}.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def _metrics_cell(report: dict | None) -> str:
    if not report:
        return "—"
    if not report.get("passed", False):
        return "❌ fail"
    m = report.get("metric", "")
    if m == "decision":
        n = report.get("n_compared", 0)
        return f"BER 0 ({n} bits)"
    mae = report.get("max_abs_err")
    tol = report.get("tolerance")
    nmse = report.get("nmse_db")
    parts = []
    if mae is not None and tol is not None:
        # Peak quantization error vs GNU Radio, in Q15 LSBs (1 LSB = 1/32768 of
        # full scale ≈ 3.05e-5). "err N / tol M LSB" = worst-case error N against
        # the derived pass threshold M — labeled so it doesn't read as a fraction.
        parts.append(f"err {mae} / tol {tol} LSB")
    if nmse is not None and nmse == nmse:  # not NaN
        # NMSE: error power relative to signal power. -65 dB SNR = the noise floor
        # is 65 dB below the signal (more negative = quieter = better).
        parts.append(f"{nmse:.0f} dB SNR")
    return " · ".join(parts) or "pass"


def _coverage_cell(report: dict | None) -> str:
    if not report:
        return "—"
    cov = report.get("coverage", {})
    bits = []
    if cov.get("edge"):
        bits.append("edge")
    if cov.get("random"):
        bits.append(f"rand×{cov['random']}")
    if cov.get("param_sweep"):
        bits.append(f"sweep×{cov['param_sweep']}")
    if cov.get("mutation"):
        bits.append("mut")
    return " ".join(bits) if bits else "—"


def render(manifest: dict) -> str:
    blocks = manifest["blocks"]
    blocks_sorted = sorted(
        blocks, key=lambda b: (b.get("tier", 9),
                               0 if b.get("status") == "done" else 1))

    n_total = len(blocks)
    n_done = sum(1 for b in blocks if b.get("status") == "done")
    n_prog = sum(1 for b in blocks if b.get("status") == "in_progress")

    lines = []
    lines.append("<!-- GENERATED by verification/tools/gen_dashboard.py — DO NOT EDIT BY HAND. -->")
    lines.append("<!-- SPDX-License-Identifier: GPL-3.0-or-later -->")
    lines.append("")
    lines.append("# Kyttar block library — status")
    lines.append("")
    lines.append(
        f"**{n_done} verified · {n_prog} in progress · {n_total} targeted.** "
        "Each Kyttar block is verified as a drop-in equivalent of its GNU Radio "
        "Companion counterpart (same parameters, output matching within Q15 "
        "quantization). “Quality” is the measured error of the verified block "
        "versus the GNU Radio reference.")
    lines.append("")
    lines.append(
        "> **Reading the quality column.** `err N / tol M LSB` — the worst-case "
        "sample error (`N`) against the derived pass threshold (`M`), in Q15 "
        "**LSBs** (1 LSB = 1/32768 of full scale ≈ 3.05e-5); pass requires "
        "`N ≤ M`. `−X dB SNR` — the **NMSE**: the error power is `X` dB below the "
        "signal power (more negative = quieter; Q15's floor is ≈ −90 dB). "
        "Decision blocks report **BER** instead. To estimate a chain's total "
        "noise, convert each block's dB to linear power (`10^(dB/10)`), sum, and "
        "convert back (`10·log10`) — the noisiest stage dominates.")
    lines.append("")
    lines.append("| Kyttar block | GNU Radio equivalent | Tier | Status | Quality (vs GNU Radio) | Coverage |")
    lines.append("|--------------|----------------------|------|--------|-------------------|----------|")
    for b in blocks_sorted:
        rep = _load_report(b["kyttar_block"]) if b.get("status") == "done" else None
        status = _STATUS_ICON.get(b.get("status", "planned"), b.get("status", ""))
        if b.get("poc"):
            # Exists and works in a demo, but not yet per-block verified.
            status += " · 🧪 proof-of-concept"
        tier = _TIER_LABEL.get(b.get("tier", 0), str(b.get("tier", "")))
        grc = f"`{b.get('grc_block', '')}`"
        lines.append(
            f"| **{b['kyttar_block']}** | {grc} | {tier} | {status} | "
            f"{_metrics_cell(rep)} | {_coverage_cell(rep)} |")
    lines.append("")
    lines.append("**Tiers** reflect verification difficulty (the build order): "
                 "tier 1 = feed-forward, tier 2 = stateful/loop, tier 3 = new "
                 "block to build. **🧪 proof-of-concept** blocks exist and work in a "
                 "demo (e.g. the coherent BPSK receiver) but have NOT yet been "
                 "through per-block GNU Radio equivalence verification — treat them "
                 "as demo-quality, not drop-in-verified. **Won't-map** blocks are "
                 "GRC blocks that do not translate to the Kyttar fabric (with a "
                 "reason in the manifest).")
    lines.append("")
    lines.append("> This table is generated from `verification/manifest.json` and "
                 "the per-block reports in `verification/reports/`. To add or "
                 "update a block, edit the manifest and commit its verification "
                 "report; regenerate with `python verification/tools/gen_dashboard.py`.")
    lines.append("")
    return "\n".join(lines)


def render_readme_summary(manifest: dict) -> str:
    """The short status summary embedded in the README between the markers.

    Lists the verified (done) blocks with their GNU Radio equivalent + quality,
    plus the headline counts. Regenerated in place so the README never drifts.
    """
    blocks = manifest["blocks"]
    n_total = len(blocks)
    n_done = sum(1 for b in blocks if b.get("status") == "done")
    n_prog = sum(1 for b in blocks if b.get("status") == "in_progress")
    done = [b for b in blocks if b.get("status") == "done"]

    lines = [_README_BEGIN]
    lines.append(
        f"**Block library: {n_done} verified · {n_prog} in progress · "
        f"{n_total} targeted.** "
        "Full table → [`verification/STATUS.md`](verification/STATUS.md).")
    lines.append("")
    if done:
        lines.append("| Verified block | GNU Radio equivalent | Quality (vs GNU Radio) |")
        lines.append("|----------------|----------------------|-------------------|")
        for b in done:
            rep = _load_report(b["kyttar_block"])
            lines.append(
                f"| **{b['kyttar_block']}** | `{b.get('grc_block','')}` | "
                f"{_metrics_cell(rep)} |")
    lines.append(_README_END)
    return "\n".join(lines)


def _update_readme(summary: str) -> bool:
    """Replace the marked block in README.md. Returns True if it changed."""
    if not README.exists():
        return False
    text = README.read_text()
    if _README_BEGIN not in text or _README_END not in text:
        return False
    pre = text.split(_README_BEGIN)[0]
    post = text.split(_README_END, 1)[1]
    new = pre + summary + post
    if new != text:
        README.write_text(new)
        return True
    return False


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if STATUS.md or the README summary is stale (CI)")
    args = ap.parse_args(argv)

    manifest = json.loads(MANIFEST.read_text())
    rendered = render(manifest)
    summary = render_readme_summary(manifest)

    if args.check:
        stale = False
        current = STATUS.read_text() if STATUS.exists() else ""
        if current.strip() != rendered.strip():
            print("STATUS.md is stale — run gen_dashboard.py and commit.",
                  file=sys.stderr)
            stale = True
        if README.exists() and _README_BEGIN in README.read_text():
            rtext = README.read_text()
            cur_sum = (rtext.split(_README_BEGIN)[1].split(_README_END)[0]
                       if _README_BEGIN in rtext and _README_END in rtext else "")
            want_sum = summary.split(_README_BEGIN)[1].split(_README_END)[0]
            if cur_sum.strip() != want_sum.strip():
                print("README block-status summary is stale — run gen_dashboard.py.",
                      file=sys.stderr)
                stale = True
        return 1 if stale else (print("dashboard up to date.") or 0)

    STATUS.write_text(rendered)
    print(f"wrote {STATUS}")
    if _update_readme(summary):
        print(f"updated {README} block-status summary")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
