# SPDX-License-Identifier: GPL-3.0-or-later
"""Generate the block-status dashboard (STATUS.md) from the manifest + reports.

The dashboard is GENERATED, never hand-edited. Source of truth:
  * ``verification/manifest.json`` — the curated target list with per-block scope,
    status, GRC counterpart, and notes; AND
  * ``verification/reports/<KyttarBlock>.json`` — a metrics record emitted by a
    block's verification run (pass, max_abs_err, nmse_db, correlation, coverage).

A block's row shows its manifest status; when a matching report exists, the row is
enriched with the measured quality metrics. This keeps the table honest — metrics
are measured, not typed — and makes a contributor's PR a clean diff (new manifest
row + report + regenerated table row).

Usage:
    python verification/tools/gen_dashboard.py            # write STATUS.md
    python verification/tools/gen_dashboard.py --check     # exit 1 if stale (CI)
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_VERIFY = Path(__file__).resolve().parents[1]
MANIFEST = _VERIFY / "manifest.json"
REPORTS = _VERIFY / "reports"
STATUS = _VERIFY / "STATUS.md"

_STATUS_ICON = {
    "done": "✅ done",
    "in_progress": "🟡 in progress",
    "planned": "⬜ planned",
    "wont_map": "⛔ won't map",
}
_TIER_LABEL = {1: "1 · feed-forward", 2: "2 · stateful/loop", 3: "3 · new GRC block"}


def _load_report(kyttar_block: str) -> dict | None:
    p = REPORTS / f"{kyttar_block}.json"
    if not p.exists():
        return None
    try:
        return json.loads(p.read_text())
    except (OSError, json.JSONDecodeError):
        return None


def _metrics_cell(report: dict | None) -> str:
    if not report:
        return "—"
    if not report.get("passed", False):
        return "❌ fail"
    m = report.get("metric", "")
    if m == "decision":
        n = report.get("n_compared", 0)
        return f"BER 0 ({n} bits)"
    mae = report.get("max_abs_err")
    tol = report.get("tolerance")
    nmse = report.get("nmse_db")
    parts = []
    if mae is not None and tol is not None:
        parts.append(f"{mae}/{tol} LSB")
    if nmse is not None and nmse == nmse:  # not NaN
        parts.append(f"{nmse:.0f} dB")
    return ", ".join(parts) or "pass"


def _coverage_cell(report: dict | None) -> str:
    if not report:
        return "—"
    cov = report.get("coverage", {})
    bits = []
    if cov.get("edge"):
        bits.append("edge")
    if cov.get("random"):
        bits.append(f"rand×{cov['random']}")
    if cov.get("param_sweep"):
        bits.append(f"sweep×{cov['param_sweep']}")
    if cov.get("mutation"):
        bits.append("mut")
    return " ".join(bits) if bits else "—"


def render(manifest: dict) -> str:
    blocks = manifest["blocks"]
    blocks_sorted = sorted(
        blocks, key=lambda b: (b.get("tier", 9),
                               0 if b.get("status") == "done" else 1))

    n_total = len(blocks)
    n_done = sum(1 for b in blocks if b.get("status") == "done")
    n_prog = sum(1 for b in blocks if b.get("status") == "in_progress")

    lines = []
    lines.append("<!-- GENERATED by verification/tools/gen_dashboard.py — DO NOT EDIT BY HAND. -->")
    lines.append("<!-- SPDX-License-Identifier: GPL-3.0-or-later -->")
    lines.append("")
    lines.append("# Kyttar block library — status")
    lines.append("")
    lines.append(
        f"**{n_done} verified · {n_prog} in progress · {n_total} targeted.** "
        "Each Kyttar block is verified as a drop-in equivalent of its GNU Radio "
        "Companion counterpart (same parameters, output matching within Q15 "
        "quantization). “Quality” is the measured error of the verified block "
        "versus the GNU Radio reference.")
    lines.append("")
    lines.append("| Kyttar block | GNU Radio equivalent | Tier | Status | Quality (err/tol) | Coverage |")
    lines.append("|--------------|----------------------|------|--------|-------------------|----------|")
    for b in blocks_sorted:
        rep = _load_report(b["kyttar_block"]) if b.get("status") == "done" else None
        status = _STATUS_ICON.get(b.get("status", "planned"), b.get("status", ""))
        tier = _TIER_LABEL.get(b.get("tier", 0), str(b.get("tier", "")))
        grc = f"`{b.get('grc_block', '')}`"
        lines.append(
            f"| **{b['kyttar_block']}** | {grc} | {tier} | {status} | "
            f"{_metrics_cell(rep)} | {_coverage_cell(rep)} |")
    lines.append("")
    lines.append("**Tiers** reflect verification difficulty (the build order): "
                 "tier 1 = feed-forward, tier 2 = stateful/loop, tier 3 = new "
                 "block to build. **Won't-map** blocks are GRC blocks that do not "
                 "translate to the Kyttar fabric (with a reason in the manifest).")
    lines.append("")
    lines.append("> This table is generated from `verification/manifest.json` and "
                 "the per-block reports in `verification/reports/`. To add or "
                 "update a block, edit the manifest and commit its verification "
                 "report; regenerate with `python verification/tools/gen_dashboard.py`.")
    lines.append("")
    return "\n".join(lines)


def main(argv=None) -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--check", action="store_true",
                    help="exit 1 if STATUS.md is stale (for CI)")
    args = ap.parse_args(argv)

    manifest = json.loads(MANIFEST.read_text())
    rendered = render(manifest)

    if args.check:
        current = STATUS.read_text() if STATUS.exists() else ""
        if current.strip() != rendered.strip():
            print("STATUS.md is stale — run gen_dashboard.py and commit.",
                  file=sys.stderr)
            return 1
        print("STATUS.md is up to date.")
        return 0

    STATUS.write_text(rendered)
    print(f"wrote {STATUS}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
